import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class', '[data-theme="dark"]'],
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  // These classes are assembled from the heatmap level at runtime. Keep the
  // authored component styles in the production CSS instead of letting the
  // content scanner purge them as unused.
  safelist: ['heatmap-cell-1', 'heatmap-cell-2', 'heatmap-cell-3', 'heatmap-cell-4', 'heatmap-cell-5'],
  theme: {
    extend: {
      fontFamily: {
        display: ['Public Sans', 'system-ui', 'sans-serif'],
        inter: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['IBM Plex Mono', 'Consolas', 'monospace'],
      },
      colors: {
        canvas: 'var(--color-bg-canvas)',
        surface: 'var(--color-bg-surface)',
        elevated: 'var(--color-bg-elevated)',
        brand: 'var(--color-bg-brand)',
        brandContainer: 'var(--color-bg-brand-container)',
        primary: 'var(--color-action-primary-bg)',
        secondary: 'var(--color-accent)',
        accent: 'var(--color-feedback-warning)',
        text: {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          inverse: 'var(--color-text-inverse)',
        },
        border: 'var(--color-border)',
        borderStrong: 'var(--color-border-strong)',
        success: 'var(--color-feedback-success)',
        alert: 'var(--color-feedback-error)',
        warning: 'var(--color-feedback-warning)',
        info: 'var(--color-feedback-info)',
        'info-surface': 'var(--color-bg-info-subtle)',
        'info-border': 'var(--color-border-info)',
        'info-strong': 'var(--color-text-info-strong)',
        'success-surface': 'var(--color-bg-success-subtle)',
        'success-border': 'var(--color-border-success)',
        'success-strong': 'var(--color-text-success-strong)',
        danger: 'var(--color-action-danger-bg-hover)',
        focusRing: 'var(--color-focus-ring)',
        topics: {
          protsendid: 'var(--color-teal-700)',
          vorrandid: 'var(--color-blue-700)',
          abivalemid: 'var(--color-amber-700)',
          defineerimine: 'var(--color-info-700)',
          'vorrandi-koostamine': 'var(--color-blue-400)',
          lahendamine: 'var(--color-red-600)',
          lineaarfunktsioon: 'var(--color-blue-750)',
          'astmed-juured': 'var(--color-teal-400)',
        },
      },
      spacing: {
        '1': '4px',
        '2': '8px',
        '4': '16px',
        '6': '24px',
        '8': '32px',
        '12': '48px',
        '16': '64px',
        '120': '30rem',
        '144': '36rem',
        '180': '45rem',
      },
      fontSize: {
        'display': ['3rem', { lineHeight: '1.15', fontWeight: '700', letterSpacing: '-0.02em' }],
        'h1': ['2.25rem', { lineHeight: '1.2', fontWeight: '700', letterSpacing: '-0.02em' }],
        'h2': ['1.75rem', { lineHeight: '1.25', fontWeight: '600', letterSpacing: '-0.01em' }],
        'h3': ['1.375rem', { lineHeight: '1.3', fontWeight: '600', letterSpacing: '-0.01em' }],
        'h4': ['1rem', { lineHeight: '1.4', fontWeight: '600' }],
        'h5': ['0.875rem', { lineHeight: '1.35', fontWeight: '600' }],
        'overline': ['0.75rem', { lineHeight: '1.3', fontWeight: '600', letterSpacing: '0.08em' }],
        'button': ['1rem', { lineHeight: '1.4', fontWeight: '600' }],
        'body-l': ['1.125rem', { lineHeight: '1.6', fontWeight: '400' }],
        'body': ['1.0625rem', { lineHeight: '1.6', fontWeight: '400' }],
        'caption': ['0.875rem', { lineHeight: '1.45', fontWeight: '400' }],
        'small': ['0.8125rem', { lineHeight: '1.4', fontWeight: '400' }],
        'mono': ['0.875rem', { lineHeight: '1.5', fontWeight: '400' }],
        '3xs': '0.75rem',
        '2xs': '0.875rem',
        xs: '1rem',
        sm: '1.125rem',
        base: '1.25rem',
        lg: '1.5rem',
        xl: '1.875rem',
        '2xl': '2.25rem',
        '3xl': '3rem',
        '4xl': '3.75rem',
        '5xl': '4.5rem',
      },
      letterSpacing: {
        tighter: '-0.05em',
        tight: '-0.025em',
        normal: '0',
        wide: '0.025em',
        wider: '0.05em',
        widest: '0.1em',
      },
      lineHeight: {
        tighter: '1.0',
        tight: '1.2',
        snug: '1.375',
        normal: '1.5',
        relaxed: '1.625',
        loose: '2',
      },
      borderRadius: {
        'none': '0px',
        'sm': '4px',
        'md': '8px',
        'lg': '12px',
        'xl': '16px',
        '2xl': '20px',
        '3xl': '24px',
        'full': '9999px',
      },
      boxShadow: {
        'card': '0 1px 3px rgba(0, 0, 0, 0.08), 0 1px 2px rgba(0, 0, 0, 0.04)',
        'card-hover': '0 4px 12px rgba(0, 0, 0, 0.08), 0 2px 4px rgba(0, 0, 0, 0.04)',
        'elevated': '0 8px 24px rgba(0, 0, 0, 0.12)',
        'dropdown': '0 4px 16px rgba(0, 0, 0, 0.1)',
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'marquee': 'marquee 30s linear infinite',
        'marquee-slow': 'marquee 45s linear infinite',
        'float': 'float 3s ease-in-out infinite',
        'bounce-slow': 'bounce 2s ease-in-out infinite',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-100%)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'gradient-brand': 'linear-gradient(135deg, var(--color-blue-700) 0%, var(--color-teal-700) 100%)',
      },
      transitionTimingFunction: {
        'standard': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'decelerate': 'cubic-bezier(0, 0, 0.2, 1)',
        'accelerate': 'cubic-bezier(0.4, 0, 1, 1)',
        'emphasized': 'cubic-bezier(0.2, 0, 0, 1)',
        'bounce': 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};

export default config;
